parameters:
  env(MESSENGER_CONSUMER_NAME): 'consumer'

framework:
  messenger:
    transports:
      default:
        dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_DB_MESSENGER)%/messages/symfony/consumer-%env(MESSENGER_CONSUMER_NAME)%?delete_after_ack=true&delete_after_reject=true"
      async:
        dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_DB_ASYNC)%/messages?delete_after_ack=true&delete_after_reject=true"
      failed:
        dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_DB_FAILED)%/failed"
      low_priority:
        dsn: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_DB_LOW_PRIORITY)%/low_priority"

